#!/usr/bin/perl -w

# script for running the xsl_indexer
# Author Sigfrid Lundberg slu@kb.dk
# Last revised $Date: 2010/06/23 09:42:43 $ by $Author: slu $
# $Id: xsl_index,v 1.5 2010/06/23 09:42:43 slu Exp $

use strict;

my $javadir = '../xslt-indexer/';
my $javahome = $ENV{'JAVA_HOME'};
my $java = "$javahome/bin/java -client -classpath ";

my $classpath = join ':',
    ("$javadir/lib/java-getopt-1.0.13.jar",
     "$javadir/lib/lucene-core-3.6.1.jar",
     "$javadir/lib/xalan-2.7.2.jar",
     "$javadir/lib/dom4j-1.6.1.jar",
     "$javadir/target/xslt-indexer-1.0.jar",
     "$javadir/lib/xercesImpl-2.9.1.jar",
     "$javadir/lib/serializer-2.7.2.jar"
);

my $start = time();

my $main = " dk.kb.dup.xsltIndexer.Driver ";
print `date`."\n";
system "$java $classpath $main @ARGV";
print `date`."\nTime consumed ";
print time() - $start;
print " seconds\n";
